resources:
  - mysql.yaml
  - firefly-iii.yaml
  - ingress-firefly-iii-cron.yaml
  - firefly-iii-importer.yaml
secretGenerator:
- name: firefly-iii-secrets
  literals:
  - db_password=$(Secrets.DbPassword)
  - app_key=$(Secrets.AppKey)
  - access_token=$(Secrets.AccessToken)
  - static_cron_token=$(Secrets.CronToken)
